export class ResManager {
  // 颜色
  static MAIN_COLOR = $r('app.color.start_window_background')
  static COLOR_PRIMARY = $r('app.color.color_primary')
  static COLOR_DEFAULT = $r('app.color.color_default')
  static COLOR_SUCCESS = $r('app.color.color_success')
  static COLOR_WARNING = $r('app.color.color_warning')
  static COLOR_DANGER = $r('app.color.color_danger')
  // 大小
  static HEADER_WIDTH = $r('app.float.header_width')
  static HEADER_WIDTH_RADIUS = $r('app.float.header_width_radius')
  static TAB_TEXT_SIZE = $r('app.float.tab_text_size')
  static TOP_TAB_TEXT_SIZE = $r('app.float.top_tab_text_size')
  // 文本
  static FONT_FAMILY = $r('app.string.font_family')
  // 图片
  static IC_HEADER = $r('app.media.ic_header_default')
  // 间距
  static SIZE_GUTTER_LG = 15
  static SIZE_GUTTER_MD = 10
  static SIZE_GUTTER_SM = 5
}
